// SPP SDK — pool contract interactions.
//
// Calls the SPP privacy pool contract on Stellar testnet via a real Groth16
// proof generated by the local spp-prover HTTP server (port 8788).
// Start the prover with: cd spp-prover && cargo run --release

import {
  Account,
  Address,
  BASE_FEE,
  Contract,
  Keypair,
  TransactionBuilder,
  nativeToScVal,
  rpc,
  scValToNative,
  xdr,
} from "@stellar/stellar-sdk";

import { DEMO_POOL, PROVER_BASE_URL, TESTNET_PASSPHRASE, TESTNET_RPC } from "./config";
import type { SppClaimResult, SppDepositResult, SppNote } from "./types";

// ---------------------------------------------------------------------------
// Internal types matching spp-prover JSON responses
// ---------------------------------------------------------------------------

interface DepositProverResponse {
  proof_scval_xdr_b64: string;
  ext_data_scval_xdr_b64: string;
  output_commitment0: string;
  output_commitment1: string;
  input_nullifier0: string;
  input_nullifier1: string;
  note: {
    amount_stroops: number;
    blinding_le_hex: string;
    commitment_be_hex: string;
  };
}

interface WithdrawProverResponse {
  proof_scval_xdr_b64: string;
  ext_data_scval_xdr_b64: string;
  output_commitment0: string;
  output_commitment1: string;
  input_nullifier0: string;
  input_nullifier1: string;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

const POLL_INTERVAL_MS = 1500;
const MAX_POLLS = 30;
const ZERO_ROOT_HEX = "0".repeat(64);

function rpcServer(): rpc.Server {
  const url =
    (typeof process !== "undefined" && process.env.NEXT_PUBLIC_STELLAR_RPC_URL) ||
    TESTNET_RPC;
  return new rpc.Server(url);
}

async function pollUntilConfirmed(server: rpc.Server, hash: string): Promise<string> {
  for (let i = 0; i < MAX_POLLS; i++) {
    await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS));
    const result = await server.getTransaction(hash);
    if (result.status === rpc.Api.GetTransactionStatus.SUCCESS) {
      return hash;
    }
    if (result.status === rpc.Api.GetTransactionStatus.FAILED) {
      const xdrB64 =
        "resultXdr" in result
          ? (result as { resultXdr: { toXDR: (enc: string) => string } }).resultXdr.toXDR("base64")
          : "unavailable";
      throw new Error(`SPP tx FAILED (hash: ${hash}): ${xdrB64}`);
    }
  }
  throw new Error(`SPP tx timed out after ${MAX_POLLS} polls (hash: ${hash})`);
}

async function checkProverHealth(): Promise<void> {
  const url = `${PROVER_BASE_URL}/health`;
  let r: Response;
  try {
    r = await fetch(url);
  } catch {
    throw new Error(
      `SPP prover not running. Start with:\n  cd spp-prover && cargo run --release`,
    );
  }
  if (!r.ok) {
    throw new Error(
      `SPP prover returned ${r.status}. Start with:\n  cd spp-prover && cargo run --release`,
    );
  }
}

async function computePoolRoot(commitments: string[]): Promise<string> {
  const r = await fetch(`${PROVER_BASE_URL}/spp/pool-root`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ commitments_be_hex: commitments }),
  });
  if (!r.ok) throw new Error(`pool-root error: ${await r.text()}`);
  const data = (await r.json()) as { root_be_hex: string };
  return data.root_be_hex;
}

/**
 * Fetch all commitments ever inserted into the pool via getEvents.
 * Returns sorted by index — this gives the correct allCommitments list for
 * Merkle path proofs during withdraw.
 *
 * NewCommitmentEvent has #[topic] on `commitment`, so the filter topic is:
 *   [Symbol("NewCommitmentEvent"), <wildcard>]
 * and the event value holds { index: u32, encrypted_output: Bytes }.
 *
 * Retention: we paginate from `oldestLedger` (the RPC retention window, ~7 days
 * on Stellar public testnet) rather than `latestLedger - 10000`. The earlier
 * 10k-ledger shortcut misses deposits older than ~14h, which causes the prover
 * to compute a Merkle path against an incomplete allCommitments list — the
 * resulting root doesn't match the pool's authoritative get_root() and the
 * Nethermind verifier rejects the proof with Error(Contract, #0).
 *
 * The pool is the only contract emitting NewCommitmentEvent in our app, so
 * scanning the full retention window is cheap in practice (a few pages of 200).
 */
async function fetchAllPoolCommitments(
  server: rpc.Server,
  poolContract: string,
): Promise<Array<{ commitment: string; index: number }>> {
  const health = await server.getHealth();
  // Scan the entire RPC retention window (~7 days on Stellar public testnet).
  // The pool is the only contract emitting NewCommitmentEvent we care about,
  // so the extra range is cheap — pagination makes it linear in event count.
  const startLedger = health.oldestLedger;

  const allRawEvents: rpc.Api.EventResponse[] = [];
  let cursor: string | undefined;

  // Paginate until we exhaust all events (each page is capped at 200 by the RPC).
  // Upper bound is generous — with a 7-day retention and one event per deposit
  // this is way more than enough for any realistic pool size.
  for (let page = 0; page < 50; page++) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const params: any = {
        filters: [{ type: "contract", contractIds: [poolContract] }],
        limit: 200,
      };
      if (cursor) {
        params.cursor = cursor;
      } else {
        params.startLedger = startLedger;
      }
      const evResp = await server.getEvents(params);
      allRawEvents.push(...evResp.events);
      // eslint-disable-next-line @typescript-eslint/no-explicitany
      cursor = (evResp as any).cursor as string | undefined;
      if (evResp.events.length < 200) break;
    } catch (e) {
      console.error("[fetchAllPoolCommitments] getEvents failed:", e);
      break;
    }
  }

  console.log(`[fetchAllPoolCommitments] total events fetched: ${allRawEvents.length}`);

  const results: Array<{ commitment: string; index: number }> = [];
  for (const ev of allRawEvents) {
    try {
      // NewCommitmentEvent value = { index: u32, encrypted_output: Bytes }
      const value = scValToNative(ev.value) as Record<string, unknown>;
      if (typeof value !== "object" || value === null || !("index" in value)) continue;

      // topic[0] = Symbol("new_commitment_event") discriminant (auto-added by soroban-sdk #[contractevent])
      // topic[1] = commitment U256 (#[topic] annotated field)
      const commitmentTopic = ev.topic[1];
      if (!commitmentTopic) continue;
      const commitmentBigInt = scValToNative(commitmentTopic) as bigint;
      if (typeof commitmentBigInt !== "bigint") continue;
      const commitment = commitmentBigInt.toString(16).padStart(64, "0");
      results.push({ commitment, index: Number(value.index) });
    } catch (err) {
      console.log("[fetchAllPoolCommitments] skipped event:", err);
    }
  }
  console.log(`[fetchAllPoolCommitments] NewCommitmentEvent count: ${results.length}`);
  return results.sort((a, b) => a.index - b.index);
}

/** Read the pool's current Merkle root from the chain (get_root view fn → U256 → BE hex 32B). */
async function readPoolRoot(server: rpc.Server, poolContract: string): Promise<string> {
  const source = new Account(Keypair.random().publicKey(), "0");
  const tx = new TransactionBuilder(source, { fee: BASE_FEE, networkPassphrase: TESTNET_PASSPHRASE })
    .addOperation(new Contract(poolContract).call("get_root"))
    .setTimeout(30)
    .build();
  const sim = await server.simulateTransaction(tx);
  if (rpc.Api.isSimulationError(sim)) throw new Error(`get_root failed: ${sim.error}`);
  if (!sim.result) throw new Error("get_root: no result");
  const raw = scValToNative(sim.result.retval) as bigint;
  // U256 → 32-byte BE hex
  const hex = raw.toString(16).padStart(64, "0");
  return hex;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Deposit `amount` into the SPP privacy pool on behalf of `recipientStellarAddress`.
 *
 * Flow:
 *   1. Health-check the local spp-prover (port 8788).
 *   2. Compute empty-pool root via POST /spp/pool-root.
 *   3. POST /spp/deposit → get real Groth16 proof + note.
 *   4. Build pool.transact(proof, ext_data, sender) and submit.
 *   5. Poll until confirmed. Return txHash + note for later claim.
 *
 * @param amount                  Token amount in stroops (7-decimal USDC).
 * @param recipientStellarAddress Stellar address of the intended recipient.
 * @param signerKeypair           Keypair that signs the deposit transaction (admin).
 * @param poolContract            Pool contract ID (defaults to DEMO_POOL).
 */
export async function depositToPool(
  amount: bigint,
  recipientStellarAddress: string,
  signerKeypair: Keypair,
  poolContract: string = DEMO_POOL,
): Promise<SppDepositResult> {
  await checkProverHealth();

  const server = rpcServer();

  // Read current pool state BEFORE deposit so we know the next free indices.
  // Events for the new deposit won't be indexed immediately after tx confirmation,
  // so we cannot rely on getEvents post-tx to find our commitment.
  const priorPoolData = await fetchAllPoolCommitments(server, poolContract);
  const priorCommitments = priorPoolData.map((d) => d.commitment);
  const nextIndex = priorCommitments.length;

  const poolRoot = await computePoolRoot([]);
  const aspNonMembershipRoot = ZERO_ROOT_HEX;

  const proverReq = {
    amount_stroops: Number(amount),
    pool_root: poolRoot,
    asp_non_membership_root: aspNonMembershipRoot,
    pool_address: poolContract,
    recipient_stellar_address: recipientStellarAddress,
  };

  const proverRes = await fetch(`${PROVER_BASE_URL}/spp/deposit`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(proverReq),
  });
  if (!proverRes.ok) {
    throw new Error(`SPP deposit proof failed: ${await proverRes.text()}`);
  }
  const resp = (await proverRes.json()) as DepositProverResponse;

  const proofScVal = xdr.ScVal.fromXDR(resp.proof_scval_xdr_b64, "base64");
  const extDataScVal = xdr.ScVal.fromXDR(resp.ext_data_scval_xdr_b64, "base64");
  const senderScVal = new Address(signerKeypair.publicKey()).toScVal();

  const account: Account = await server.getAccount(signerKeypair.publicKey());
  const tx = new TransactionBuilder(account, {
    fee: BASE_FEE,
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(
      new Contract(poolContract).call("transact", proofScVal, extDataScVal, senderScVal),
    )
    .setTimeout(30)
    .build();

  const prepared = await server.prepareTransaction(tx);
  prepared.sign(signerKeypair);

  const sent = await server.sendTransaction(prepared);
  if (sent.status === "ERROR") {
    throw new Error(
      `SPP depositToPool ERROR: ${sent.errorResult?.toXDR("base64") ?? "unknown"}`,
    );
  }

  const txHash = await pollUntilConfirmed(server, sent.hash);

  // Build allCommitments from prior state + our two new commitments.
  // The pool always inserts at nextIndex and nextIndex+1 in the same transact call.
  const allCommitments = [
    ...priorCommitments,
    resp.note.commitment_be_hex, // output_commitment0 — the one we'll claim
    resp.output_commitment1,     // output_commitment1 — change output
  ];
  const leafIndex = nextIndex;

  // Read the authoritative pool root AFTER our deposit landed (needed for withdraw proof).
  const poolRootAfterDeposit = await readPoolRoot(server, poolContract);

  const note: SppNote = {
    commitment: resp.note.commitment_be_hex,
    amount: Number(amount),
    blinding: resp.note.blinding_le_hex,
    leafIndex,
    allCommitments,
    poolRootAfterDeposit,
  };

  return { txHash, note, poolContract };
}

/**
 * Claim (withdraw) from the SPP privacy pool using a note from a prior deposit.
 *
 * Flow:
 *   1. Health-check the local spp-prover.
 *   2. Compute pool root from the note's tracked commitments.
 *   3. POST /spp/withdraw → get real spend proof.
 *   4. Build pool.transact(proof, ext_data, sender) and submit.
 *   5. Poll until confirmed. Return txHash + amount.
 *
 * @param note             Note returned by depositToPool (must have blinding, leafIndex, allCommitments).
 * @param recipientKeypair Keypair that signs the claim transaction (employee).
 * @param poolContract     Pool contract ID (defaults to DEMO_POOL).
 */
export async function claimFromPool(
  note: SppNote,
  recipientKeypair: Keypair,
  poolContract: string = DEMO_POOL,
): Promise<SppClaimResult> {
  if (!note.blinding || note.leafIndex === undefined || !note.allCommitments) {
    throw new Error(
      "claimFromPool: note is missing blinding, leafIndex, or allCommitments. " +
        "Use the note returned by depositToPool.",
    );
  }

  await checkProverHealth();

  // Use the root stored after deposit (authoritative, read from chain).
  // If absent (old note format), query the pool contract directly.
  const claimServer = rpcServer();
  const poolRoot = note.poolRootAfterDeposit
    ?? await readPoolRoot(claimServer, poolContract);
  const aspNonMembershipRoot = ZERO_ROOT_HEX;

  const proverReq = {
    withdraw_amount_stroops: note.amount,
    pool_root: poolRoot,
    asp_non_membership_root: aspNonMembershipRoot,
    withdraw_recipient: recipientKeypair.publicKey(),
    input_note: {
      amount_stroops: note.amount,
      blinding_le_hex: note.blinding,
      all_pool_commitments_be_hex: note.allCommitments,
      leaf_index: note.leafIndex,
    },
  };

  const proverRes = await fetch(`${PROVER_BASE_URL}/spp/withdraw`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(proverReq),
  });
  if (!proverRes.ok) {
    throw new Error(`SPP withdraw proof failed: ${await proverRes.text()}`);
  }
  const resp = (await proverRes.json()) as WithdrawProverResponse;

  const proofScVal = xdr.ScVal.fromXDR(resp.proof_scval_xdr_b64, "base64");
  const extDataScVal = xdr.ScVal.fromXDR(resp.ext_data_scval_xdr_b64, "base64");
  const senderScVal = new Address(recipientKeypair.publicKey()).toScVal();

  const server = rpcServer();
  const account: Account = await server.getAccount(recipientKeypair.publicKey());
  const tx = new TransactionBuilder(account, {
    fee: BASE_FEE,
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(
      new Contract(poolContract).call("transact", proofScVal, extDataScVal, senderScVal),
    )
    .setTimeout(30)
    .build();

  const prepared = await server.prepareTransaction(tx);
  prepared.sign(recipientKeypair);

  const sent = await server.sendTransaction(prepared);
  if (sent.status === "ERROR") {
    throw new Error(
      `SPP claimFromPool ERROR: ${sent.errorResult?.toXDR("base64") ?? "unknown"}`,
    );
  }

  const txHash = await pollUntilConfirmed(server, sent.hash);
  return { txHash, amount: note.amount };
}
